name: Send Birthday Emails

on:
  schedule:
    - cron: "0 6 * * *"   # Runs every day at 6 AM UTC
  workflow_dispatch:       # Allow manual trigger

jobs:
  birthday-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          pip install pandas openpyxl smtplib email-validator

      - name: Run birthday script
        run: python send_birthday.py
        env:
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}

